Update 1-run_nginx_as_nginx

diff --git a/0x12-web_stack_debugging_2/1-run_nginx_as_nginx b/0x12-web_stack_debugging_2/1-run_nginx_as_nginx
--- a/0x12-web_stack_debugging_2/1-run_nginx_as_nginx
+++ b/0x12-web_stack_debugging_2/1-run_nginx_as_nginx
@@ -23,6 +23,13 @@ sed -i "s/listen\s*80;/listen $LISTEN_ADDRESS:$LISTEN_PORT;/" "$NGINX_CONF"
 
 sed -i "s/user\s*www-data;/user $NGINX_USER $NGINX_GROUP;/" "$NGINX_CONF"
 
-service nginx restart
+if ! service nginx status >/dev/null 2>&1; then
+  echo "Error: Nginx service is not running."
+  exit 1
+fi
+
+service nginx stop
+
+service nginx start
 
 echo "Nginx has been configured to run as $NGINX_USER user and listen on $LISTEN_ADDRESS:$LISTEN_PORT."
